---
langs: [fr_FR, en_US]
baseurl: "/jeedom-plugins-docs" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "Dino Plugins Documentations"
description: "Ceci est la documentation des plugins créés par Dino de la solution domotique Jeedom."
author: "Dino"
image: https://www.jeedom.com/site/logo.png
forum: https://community.jeedom.com
